image: dark2011/qt-5.12.3
before_script:
        - sudo apt-get install -y -qq gcc-mingw-w64-i686 g++-mingw-w64-i686 mingw-w64-tools nsis

  #- pwd
  #- sudo apt-get install -y mingw-w64
  #- set PATH=%PATH%;C:\Qt\Tools\mingw730_64\bin\mingw32-make.exe
build:
  script:
    - dir
    - qmake GE_PoC.pro
  #  - bash anusha.sh
  #  - mingw32-make
   # - i586-mingw32msvc-g++ -o essai.exe main.cpp
   # - echo $PATH
    #- ls /usr/bin
    - mingw32-make
    - dir
 # tags:
  #  - ge-Win
    
