image: dark2011/qt-5.12.3
before_script:
  - set PATH=%PATH%;C:\Qt\Tools\mingw730_64\bin\mingw32-make.exe
build:
  script:
    - dir
    - qmake GE_PoC.pro
    - mingw32-make
    - dir
 # tags:
  #  - ge-Win
    
